#Deployment
#https://dev.to/whitphx/how-to-deploy-streamlit-apps-to-google-app-engine-407o

runtime: python
env: flex

runtime_config:
  python_version: 3

entrypoint: streamlit run streamlit-app.py --server.port $PORT


automatic_scaling:
  max_num_instances: 1
  min_num_instances: 0

# Or manual scaling as below:
# manual_scaling:
#   instances: 1